### ISSUE TITLE
[Bug] Duplicate <header> Elements in the Vocabulary Docs Documentation

### ISSUE THREAD

**Issue by Dev-JoyA** [creativecommons/vocabulary#101]
## Description
The Vocabulary Docs documentation includes two `<header>` tags on a single page, which violates HTML structure guidelines. To ensure proper semantics and maintain clarity, there should be only one `<header>` tag. The second instance, currently under `body > main`, can be replaced with a `<section>` tag for uniqueness, though a `<div>` could also be used. A `<section>` tag is preferred to maintain semantic meaning.

## Reproduction

1.  Open the url of the Vocabulary docs [https://vocabulary-docs.netlify.app/](url), In the Header-Global Area, there is an instruction of where the header should be placed which is directly after opening the body tag
2. In the same page , where the Page Header -Region is, there also an instruction for where header should be placed which body>main>header
4. See error.

## Expectation

All Html page that follows the vocabulary docs layout should have only one header 
There should only be one <header> element at the top of the page, containing global navigation or introductory content. The <header> directly after the opening <body> tag is acceptable; however, any additional heading within the <main> content should use a <section> tag instead of a second <header>, maintaining proper HTML semantics and avoiding confusion.

## Screenshots

This should be left like this 
![Screenshot 2024-10-05 at 13 12 06](https://github.com/user-attachments/assets/1ecfdb43-11ec-4e56-8663-2a690b28cd9d)

This should be changed to a section tag
![Screenshot 2024-10-05 at 13 11 05](https://github.com/user-attachments/assets/081c19cd-c913-4f66-82a5-5ca7aca92edb)

## Environment

 - Device: laptop
 - Browser: chrome

## Resolution

- [x ] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
HI @Dev-JoyA and thanks for highlighting this!

The second `header` present are within a code section and is required to show the markup. This is one of those instances that HTML doesn't completely account for, which is showing HTML example code within an HTML document. Putting a `section` around that entire area still wouldn't resolve the semantics, as the `header` within the `code` element would now be assumed to be a landmark of that section when it is in fact not. Additionally, to bridge this gap slightly the HTML markup within the `code` elements is escaped with JavaScript at page load, this is not a perfect implementation, but it does reach a stable compromise at this time. This would mean that at load the second `header` should be ignored as it is now escaped.

Additionally, a page can have multiple `header` elements. A page should not have multiple `h1` elements, though.

> The `<header>` element defines a [banner](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/banner_role) landmark when its context is the [`<body>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body) element. The HTML header element is not considered a banner landmark when it is descendant of an [`<article>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article), [`<aside>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside), [`<main>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main), [`<nav>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav), or [`<section>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) element. 
--(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header)

Provided it is nested correctly a page can have multiple header elements, and given the gap-case here, the JavaScript escaping, and the context of use, I don't see that there needs to be a change; or that there is a change that could be made to satisfy the available context of necessary use, compromise, and semantics as it intersects with a variety of areas.

Closing for now.
