### ISSUE TITLE
[Bug] Fix Improper <br> Usage and Mismatched </ul> and </article> Tags in program-index.html

### ISSUE THREAD

**Issue by Arinzelight** [creativecommons/vocabulary#115]
## Description
Two syntax errors were found in program-index.html:

1.  A `<br>` tag is placed inside a `<p>` element and includes an unnecessary closing tag.
2.  A `</ul>` tag is incorrectly closed with an `</article> `tag

## Reproduction

1. Check program-index.html on line 225:25, where the `<br> `tag inside a paragraph element results in a SyntaxError: Void elements do not have end tags.
2. Check line 201, where an `</ul>` tag is incorrectly closed with an </article> tag.

## Expectation

1. The `<br>` tag should not have a closing tag, as it is a void element.
2. The `<ul>`element should be correctly closed with `</ul>`.

## Screenshots
![syntax-error1](https://github.com/user-attachments/assets/7a869da3-796b-48c5-bd91-760d40cdb588)
![syntax-error2](https://github.com/user-attachments/assets/f528c324-9907-453a-a913-bd83ff2f03f5)

## Environment
File: program-index.html
Lines: 225:25, 201

## Additional context
Proper HTML syntax should be maintained by ensuring:

1. Void elements like <br> do not have end tags.
2. Opening and closing tags are correctly paired.

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by ObuliAbraham** [comment]
this is a good one... i love it....
