### ISSUE TITLE
[Feature] Implement a Unified 404 error Page

### ISSUE THREAD

**Issue by Netacci** [creativecommons/vocabulary#118]
## Problem

The 404 error pages on the LegalDB, Search Portal, and OpenSource websites are inconsistent, and the design system currently does not provide a unified 404 page. This results in a lack of cohesion across the different platforms

LegalDb website

![legal-404](https://github.com/user-attachments/assets/406f0025-755a-4199-bc04-93da85d91e3d)

Opensource website

![oo-404](https://github.com/user-attachments/assets/856083e9-2125-4279-bc47-e76f512f4d9d)

Search portal

![search 404](https://github.com/user-attachments/assets/270ff9be-a72a-471b-a0fa-245492a2c2b2)

## Description

This feature will implement a unified 404 error page and ensure consistency across ancillary websites. A centralized design will provide a better user experience and improve the overall aesthetic consistency of the brand.

## Alternatives

Continue with separate 404 pages for each site, but this might create a disjointed user experience.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
Hi @Netacci and thank you for your excitement. This is a duplicate of #1 Please verify an Issue doesn't already exist when creating one. 

Please see the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/)

Closing as duplicate.

**Comment by Netacci** [comment]
Okay thanks for pointing that out. @possumbilities
