### ISSUE TITLE
[Bug] Footer misdocumented as header under the Footer section of theVocabulary documentation

### ISSUE THREAD

**Issue by egbadon-victor** [creativecommons/vocabulary#123]
## Description

When going through the vocabulary documentation, there is a typographical error that may confuse some who read the documentation
Under the **"Footer - Global Area"** section, the statement, **"The Global Header component contains several sub-elements."** was made. Immediately after, followed by the sub-components of the footer. This now becomes obvious that it was meant to say 
"The Global **Footer** component contains several sub-elements." and then go ahead to list the Global Footer sub-components.

## Reproduction

1. Visit the [vocabulary documentation page](https://vocabulary-docs.netlify.app/) 
2. Scroll to the **"Components"** section of the documentation
3. Scroll to the Footer - Global area subheading under the components section
4. The error is contained in the second line after the "permalink"

## Expectation

You would see the desceribed scenario and the typographical error

## Screenshots

![image](https://github.com/user-attachments/assets/7da73aa8-87a3-4e89-92b7-ce4fafef97dc)

## Environment

 - Problem is not enviroment specific

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by lillian-busingye** [comment]
<img width="1266" alt="footer" src="https://github.com/user-attachments/assets/3279bef0-ce22-4cf8-bee0-79217549653e">
Fixed issue

**Comment by possumbilities** [comment]
Hi @lillian-busingye this is a closed Issue already corrected by: 
- #127
