### ISSUE TITLE
[Bug] Global footer menu not responsive enough

### ISSUE THREAD

**Issue by FatumaA** [creativecommons/vocabulary#125]
## Description
The global footer component's menu links and social icon menu sections are not properly responsive. They remain quite large on smaller screens.

## Reproduction
1. Run the repo locally
2. Open the specimen/index.html page in live server mode
3. Paste in the footer component definition from the [docs](https://vocabulary-docs.netlify.app/#components)
4. Notice the menu links and the icons
5. Resize to mobile view, notice the menu is now in a column but still the same size
6. The icons also look large and they stay the same size

## Expectation
Footer links and icons should be smaller on mobile. They look much bigger than the other text in the footer.

## Screenshots
![Screenshot 2024-10-07 at 19 52 33](https://github.com/user-attachments/assets/55b056e3-4990-4c17-a1f6-37c2f705ddc0)

## Environment
Tested on Chrome

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
I think here that remaining larger would aide in the ability give them maximum touch area for Accessibility. If anything this might be a matter of aesthetic preference and not an element of things not being Responsive. Responsive on mobile does not necessarily mean things shrink in size, to the contrary it is often a better use case for items to not shrink, or in some cases grow on smaller screens to maintain adequate touch targets and readability. 

Closing for now, and likely out of scope.

**Comment by FatumaA** [comment]
In that case, shouldn't all the clickable elements be the same size?
