### ISSUE TITLE
[Bug] Typographical Error in vocabulary documenation

### ISSUE THREAD

**Issue by egbadon-victor** [creativecommons/vocabulary#138]
## Description

Under the Data Points - Singular - Block section, a typographical error is observed in Expected context definition.

`article.case-studies > ul > li > article-data-point`

Here we see the `article-data-point` is represented. This would mean that there is a html tag called `article-data-point`, which is not the case. Based on the code snippet provided in the documentation, this should be `article.data-point`

## Reproduction

1. Fork and clone the creativecommons/vocabulary repo to your local machine
2. Open the repo on your preferred code editor.
3. Open the `docs/index.html` file on your browser of choice
4. Scroll to the Data Points - Singular - Block section
5. See error under the Expected Context section.

## Expectation

You would see the typo as described above.

## Environment

 - Problem is not enviroment specific

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
@OmarAmeen01 If you comment here I can assign you.

**Comment by OmarAmeen01** [comment]
yes assign it to me

**Comment by possumbilities** [comment]
Resolved by: 
- #147 

Closing as completed.
