### ISSUE TITLE
[Bug] Images in home-index.html is not displaying

### ISSUE THREAD

**Issue by vickova** [creativecommons/vocabulary#141]
## Description
The images on some of the pages aren't displaying. They all seems to be linking to a non-existing image file in a folder called "imgs".

## Reproduction
1. Check the src attribute of the  img tags that are the direct children of the 'figure" tag within the "article" tag with the class = "case-studies"

## Expectation
The images in the alt links should display on the page instead of linking to a broken non-existing file. As much as this can be an intentional decision by the team, I will suggest that at least an image be displayed for all.

## Screenshots
![Screenshot (304)](https://github.com/user-attachments/assets/35a54031-1e89-4b7c-9d7a-76fe880cf787)

## Environment
 File: home-index.html
Lines: 115, 121, 127, and 133

## Additional context
Although this might not have so much effect since the alt text are displaying, but having these images display will help improve both the user interface and the user experience.

## Resolution
- [ ] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
This is a known issue and already documented by:
- #39 

Marking as duplicate. Please verify Issues don't already exist prior to creating them.

Please see the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/)
