### ISSUE TITLE
[Bug] Missing `<meta charset="UTF-8">` in Head of All contexts and tests

### ISSUE THREAD

**Issue by Faith-K-commits** [creativecommons/vocabulary#156]
## Description
The `<meta charset="UTF-8">` tag is missing in the `<head>` section of all context and tests files. This tag is essential for proper character encoding and should be included in all HTML documents.

## Reproduction
1. Open any context HTML file (e.g., [program-page.html]
2. Inspect the` <head> ` section.
3. Notice the absence of the `<meta charset="UTF-8">`  tag.

## Expectation
The `<meta charset="UTF-8">` tag should be present in the <head> section of all context HTML files.
## Screenshots
![meta-issue](https://github.com/user-attachments/assets/f6f6210b-4f4d-4d9e-af11-39c628d0b649)

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Additional context
 This issue affects all context HTML files and should be addressed globally.

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
I updated the description to include all the tests as well. Everything within the `specimen` folder applicable should be corrected.

**Comment by possumbilities** [comment]
Fixed by: 
- #217

Closing.
