### ISSUE TITLE
[Bug] Placeholder Links Missing `#` Value

### ISSUE THREAD

**Issue by Faith-K-commits** [creativecommons/vocabulary#157]
## Description
Placeholder links in the context HTML files are missing the default `#` placeholder value. These should be set to `#` as proper placeholders.

## Reproduction
1. Open any context HTML file (e.g., [program-page.html]
2. Inspect the `href` attributes in the navigation links.
3. Notice the absence of the `#` placeholder value.

## Expectation
The `href` attributes in the navigation links should have the # placeholder value.

## Screenshots
![placeholder_issue](https://github.com/user-attachments/assets/0abb3b1c-4e72-443b-a4f7-44258adbb1df)

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by egbadon-victor** [comment]
@possumbilities I would love to work on this issue

**Comment by iyinolawumi** [comment]
This has been sorted and closed. Well done @egbadon-victor @Faith-K-commits and thank you @possumbilities
