### ISSUE TITLE
[Bug] Incorrect Closing of `br` tags in some html files

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/vocabulary#158]
## Description
In the html files below, the br tag is wrongly closed there by preventing prettier from formatting the code.

in docs folder:
1. index.html

In specimen > contents:
1. archive-page
2. blog-index
3. blog-post
4. default-page
5. home-index
6. license-page
7. person-page
8. program-index
9. search-index
10. team-index
11. walkthrough-page

in tests folder:
1. index-logo
2. index.html
3. product-logo

The incorrect way the br tag is written prevents prettier from formatting the code.

1.The br tag should be correctly closed, this will enable prettier work without throwing error(s).

- [ ] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
@SisiVero Please verify if this is present within only this context, or if it is present within all the other context's footers as well. If so all the footer areas where this is occurring should be documented on this Issue, by listing out each context where this is happening; and the title of this Issue updated to match and more accurately describe the matter.

Additionally, to resolve this, the `</br>` tag should be changed to a self terminating tag `<br />`, there is no need to add an opening tag.

**Comment by SisiVero** [comment]
Hi @possumbilities , I'll check and revert. 
Thank you, I entirely forgot that br is a self closing tag. It's been long I used one.

**Comment by SisiVero** [comment]
hi @possumbilities , I've updated the issue with relevant details. Do check. Thank you.

**Comment by possumbilities** [comment]
@SisiVero Thanks for the revisions! 

Moved to https://github.com/creativecommons/vocabulary/labels/%F0%9F%8F%81%20status%3A%20ready%20for%20work

**Comment by SisiVero** [comment]
Thank you
