### ISSUE TITLE
[Feature] Repeated Header and Footer Code Across Multiple Pages

### ISSUE THREAD

**Issue by mo-gbolahan** [creativecommons/vocabulary#163]
## Problem

Repeated Header and Footer Code Across Multiple Pages
## Description

Currently, the header and footer components are hardcoded individually into each page of the codebase. This means that the same HTML for the header and footer is repeated across multiple files.

As a result, if any change needs to be made to the header or footer (e.g., updating links, adding a new menu item, or modifying branding), it has to be done manually on every page one by one. This approach is inefficient and error-prone, increasing the risk of inconsistent updates across pages.

## Alternatives

- Consistency: Ensures all pages are updated uniformly when changes are made to the header or footer.
- Maintainability: Reduces the amount of redundant code and simplifies future updates.
- Efficiency: Saves time by enabling updates in one place rather than across multiple files.

## Impact:

- Manual updates: Changes to header/footer elements require editing multiple files manually.
- Increased maintenance time: This leads to unnecessary time spent on repetitive tasks.
- Potential for inconsistency: Human error may lead to inconsistencies across different pages if updates are not applied uniformly.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
While manual in nature, this is the current intended structure of the framework, as its static html. 

Changes here would be out of scope of the project at current.
