### ISSUE TITLE
[Bug] Double </a> (link) closing tags in index.html

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/vocabulary#168]
## Description
In index.html of the docs folder, there currently are two closing </a> tags in line 62 of the code, this prevents prettier from working.

##screenshot
<img width="797" alt="doubleClosingTag" src="https://github.com/user-attachments/assets/b304dac3-3bd7-41a6-91fd-daf19ff9312c">

## Reproduction

1. Go to docs folder
2. Open index.html
3. Try formatting the code using prettier.
4. Check line 62.
5. See error.

## Resolution
- [ ] I would be interested in resolving this bug.

**Comment by SisiVero** [comment]
@possumbilities , I am currently checking other files to see if any of them has the same error. Pls hold on with moving the issue.

**Comment by SisiVero** [comment]
> @possumbilities , I am currently checking other files to see if any of them has the same error. Pls hold on with moving the issue.

This only affects the index.html file in docs folder

**Comment by possumbilities** [comment]
Hi @SisiVero as a practice, instead of just listing the line number it might be helpful to provide a screenshot and/or quote of the affected area of code.

**Comment by SisiVero** [comment]
Hi @possumbilities , noted.
I'll attach a screenshot asap.
Thank you for the tip.

**Comment by SisiVero** [comment]
Hi @possumbilities , I've added a screenshot and updated the title of the issue as well. Do check, thank you.

**Comment by jessyovia** [comment]
Hi @SisiVero, I have been able to resolve the issue. please find attached.
<img width="691" alt="image" src="https://github.com/user-attachments/assets/a2ed9cf9-f58f-44df-bf81-5a63a9d900c1">

**Comment by SisiVero** [comment]
Hi @jessyovia , first I'd like to acknowledge your enthusiasm. 
However, this issue is not yet marked ready to be worked on.
I left you a message on slack.
Alternatively, you can go through the CC-guides repository, it contains everything you need to know:
https://github.com/SisiVero/CC-guides

**Comment by SisiVero** [comment]
Hi @jessyovia , you can give this a shot now as it has been set "ready for work"

**Comment by jessyovia** [comment]
Hi @SisiVero,

Thank you for the update! I’ll go ahead and proceed with the task now that
it’s marked as ready for work.

I appreciate the support, and I'll reach out if I need further
clarification.

Best regards.

**Comment by egbadon-victor** [comment]
@possumbilities I would love to work on this issue. You can assign to me.
