### ISSUE TITLE
[Bug] <link> tags not closed in all contexts pages

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/vocabulary#170]
## Description
1. Currently in all the html files in context folder, the <link> tags in lines 8, 9, 10 and 13 are not closed.
2. In index-logo and product-logo files of tests folder, the <link> tags in line 8 of each files are not closed.
3. In index.html of docs folder, the <link.> tags in lines 8 and 125 are not closed.

## Reproduction

1. Go the listed folders
2. Open each file listed.
6.Check the lines mentioned
7. See error.

## Expectation
The <link> tags should be closed as it is a self terminating tag. 

## Screenshots
Below are screenshots from the codes:
contexts files:
<img width="638" alt="contextsPages" src="https://github.com/user-attachments/assets/4e3d8ea1-796c-4655-b961-c92f75e139c9">

index-logo:
<img width="358" alt="index-logo" src="https://github.com/user-attachments/assets/a7d8644b-cf67-4eb2-a838-937b954400d7">

index.html (docs folder)
<img width="441" alt="docsindex html" src="https://github.com/user-attachments/assets/19a81963-1101-4415-8c89-44ff9bb77fc8">

- [ ] I would be interested in resolving this bug.

**Comment by mercybassey** [comment]
Hi! I am an Outreachy applicant for the December 2024 Cohort. Can I work on this?

**Comment by OmarAmeen01** [comment]
@possumbilities I think  this issue should be closed because `<link >` tag does not need to  have a closing tag  because it does not contains any content that needed to be displayed on web page .

**Comment by SisiVero** [comment]
Thank you @possumbilities

**Comment by SumaiyaaRq** [comment]
I have submitted a PR request for this issue.

**Comment by SisiVero** [comment]
Hi @SumaiyaaRq , since your PR has been merged, you can go ahead and record it as one of your contributions. Well done.

**Comment by SumaiyaaRq** [comment]
Hey @SisiVero ,Thank you!
I will do that real soon😃
