### ISSUE TITLE
[Bug] Enhance Client-Side Email Validation in Newsletter Form (Footer)

### ISSUE THREAD

**Issue by wendy640** [creativecommons/vocabulary#174]
## Description
The newsletter subscription form has an email field with the required attribute, which ensures the field is filled out before submission. However, additional client-side validation should be implemented to enhance form validation and ensure that only valid email addresses are submitted.

## Reproduction
1. Navigate to the page containing the newsletter form.
2. Enter an invalid email address (e.g., "email@domain").
3. Submit the form.
4. Notice that the form does not perform full email format validation on the client-side.

## Expectation
The email field should not only be required but also perform robust client-side validation to ensure that a properly formatted email address is entered before submission.

## Screenshots
![Screen Shot 2024-10-11 at 1 10 26 PM](https://github.com/user-attachments/assets/2665830c-095d-4847-a411-90915feb44d4)
![Screen Shot 2024-10-11 at 1 11 00 PM](https://github.com/user-attachments/assets/65f2b42d-2bd6-4966-896c-d8c2d1f8bcba)

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Additional context
Consider adding a regex pattern for email validation or using HTML5’s pattern attribute to validate the email format, ensuring the user input matches a proper email address format.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
Thank you for the work here, however this is a duplication of:

-  #121. 

In the future please do not open Issues that duplicate the work of other Issues, please instead: 
1. Be sure the Issue you are creating does not already exist first
2. If an Issue already exists, add additional input to that Issue if useful as a comment, if you believe something is missing.

Please also see the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/)

**Comment by wendy640** [comment]
thank you for the feedback
