### ISSUE TITLE
[Bug] Vocabulary css style rules not being followed.

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/vocabulary#177]
## Description
In the vocabulary.css file, the style rule or guides for writing style rules which are:
Style rules are written with two sections
at current, separated by an empty line.

1. for layout, positioning, and related.

2. for visual configuration such
as color, font, background, etc.

are not being followed in some of the css styles.

## Reproduction

1. Calmly read through the written css styles.
2. Ensure that they adhere to the guide; layout in the first section, and empty line, then visuals in the second section.

## Expectation
1. Layout styling should be written in the first section.
2. An empty line should demarcate the first section from the second section. 

- [ ] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
Moved this issue as work within the `vocabulary.css` file should take place within Vocabulary itself

**Comment by Queen-codes** [comment]
Hi! I'm leaving this comment here as suggested so this issue can be assigned to me. Thank you @possumbilities
