### ISSUE TITLE
[Bug] There is a Spelling Mistake of Ancillary in the Code 

### ISSUE THREAD

**Issue by Raja-Abrar-Khan** [creativecommons/vocabulary#184]
## Description
There is a misspelling of "Ancillary" in the website UI, as well as in the HTML file located in the docs folder. This spelling error should be corrected for professionalism. After correcting it in the docs/index.html file, we must also update all instances where the class with the incorrect spelling is used, specifically in src/css/vocabulary.css. This will improve the overall quality of our website.

## Reproduction
1. Navigate to the docs folder in the Vocabulary project.
2. Open the index.html file and check lines 207 and 248.
3. You will see the misspelling of "Ancillary" there.
4. Verify the error in the UI.

## Screenshots

![Screenshot 2024-10-13 021523](https://github.com/user-attachments/assets/29359e78-f16c-4791-bc0e-a00a916aa29d)
![Screenshot 2024-10-13 021531](https://github.com/user-attachments/assets/0ed3ea1d-1c74-4908-8370-5cdef15d5a99)
![Screenshot 2024-10-13 021852](https://github.com/user-attachments/assets/c454a8ae-3ef1-4e90-97b1-45a1aa870d3c)
![Screenshot 2024-10-13 021936](https://github.com/user-attachments/assets/251d90c7-c2b3-4850-a99f-739fe5cd30af)

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
Hey @Raja-Abrar-Khan Good spot. 

Any PRs submitted against this would need to correct ALL occurrences of this.

**Comment by Raja-Abrar-Khan** [comment]
I’ve corrected all occurrences of "Ancillary" throughout the codebase, including the HTML and CSS files. I had made the pr but it the issue was not ready to work ,now i know that we should made a pr on the  issues that are ready to work. Let me make a pr again then merge It , Thanks @possumbilities  again to guide me .
