### ISSUE TITLE
[Feature] Refactor JavaScript Code for Improved Readability: Declare const Variables at the Top

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/vocabulary#185]
## Problem
The current JavaScript code for managing the expand/collapse functionality of UI components is not organized. The const variables are scattered throughout the code, which can make it difficult to read and maintain.

## Description
I propose restructuring the JavaScript code to declare all const variables at the top of the script. This change enhances readability and organization, allowing for easier maintenance and updates in the future.

By grouping all variable declarations together, it becomes clearer which elements are being manipulated by the subsequent event listeners, improving the overall flow of the code.

## Alternatives
An alternative would be to keep the existing structure, but this would make the code less organized and potentially more difficult to navigate as the codebase grows. The proposed change is better as it promotes clarity and maintainability.

## Additional context
This practice of declaring variables at the top is a widely accepted coding standard, improving code quality and making it easier for others to understand the code quickly.

Current js code:
<img width="462" alt="cuurentJs" src="https://github.com/user-attachments/assets/c1c4c795-acb9-4236-841f-cfda7c32f6db">

Proposed code:
<img width="454" alt="rearrangedJS" src="https://github.com/user-attachments/assets/6e84aefc-dc15-41d4-8585-e1c73949e8ca">

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
Hi @SisiVero 

The current structure keeps both the values and the functionality coupled tightly for more modular editing and expansion, which make future changes for the Design System less error prone, and more stable.

This is intended structure, and should stay as-is in the current implementation. 

Closing as intended behavior/structure.

**Comment by SisiVero** [comment]
Okay @possumbilities , thank you.
