### ISSUE TITLE
[Bug] `person-page` context profile image does not support mixed aspect ratios, expects a smaller square

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/vocabulary#19]
## Description
The absolute positioning behavior of the profile image does not interact with the flow of content, or its parent container. This means taller images spill over the parent container if its not tall enough, often when the description/bio is left empty or contains very little copy. 

## Reproduction

1. Go to https://creativecommons.org/person/javahercreativecommons-org/
2. See error.

## Expectation
Either the profile image should crop to a consistent size, preventing overflow, or the header area of the page should support mixed aspect ratios of the image. The latter solution would likely involve reconsidering how layout is implemented entirely for this section, leaning on an approach which does not leave the regular flow of content in its influence.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Demi-la** [comment]
I am interested in working on this

**Comment by possumbilities** [comment]
@Demi-la 

Please see [Contribution Guidelines — Creative Commons Open Source](https://opensource.creativecommons.org/contributing-code/) for how we manage issues and PRs.

We generally don't assign issues prior to resolution. Instead of asking for issues to be assigned, do the work and submit a pull request (PR). Even if multiple people submit PRs for the same issue, multiple ideas and implementations strengthen the final product.

For work program applicants, each can all list their own PRs on their application. It is the quality of work that is important, not whether it is merged.

**Comment by OmarAmeen01** [comment]
hey @possumbilities  i can fix this issue but I need more information like can i add Html  to it to make it work properly i think the figure should not be absolute i allowed using html i can fix this in two lines of code  using flex box need your response on that
