### ISSUE TITLE
[Bug] Remove empty rulesets in vocabulary.css

### ISSUE THREAD

**Issue by Queen-codes** [creativecommons/vocabulary#194]
## Description
While reviewing the `vocabulary.css` file, I noticed some empty rulesets present in the file, which add to the clutter and should be removed for improved clarity and consistency.

## Reproduction

1. Open the `vocabulary.css` file
2. Read through carefully and notice the inconsistencies.
3. See error.

## Expectation
no empty rulesets.

## Screenshots
<img width="894" alt="Screenshot 2024-10-14 at 09 46 31" src="https://github.com/user-attachments/assets/a62e051e-7c15-4cf1-a476-45f677c83628">

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
Hi @Queen-codes 

* Inconsistent units: this is intended, varying units have varying applicable purposes.
* Empty Rulesets: there were in most cases placeholders, but could be removed for clarity
* Duplicate Rules: there is some larger structural that needs doing here, however some duplication if it keeps things modular is desired.

I would ask that you split this Issue up into more concise pieces. Perhaps moving this Issue's title and description to cover the Empty Rulesets.

There's larger work that would need to happen first before Duplicate Rules could be reduced down in a stable fashion, so I wouldn't include that in this Issue.

**Comment by Queen-codes** [comment]
Hi @possumbilities 

Thank you for the feedback and for explaining why there are varying units. I’ve edited the issue to focus solely on the empty rulesets, as per your suggestion.

I have a question, instead of removing the empty rulesets completely, would it be better to comment them out in case there's a need to add rules to those selectors in the near future? I'd like to know what you think.
