### ISSUE TITLE
[Bug] Stray end tag “span”.

### ISSUE THREAD

**Issue by vickova** [creativecommons/vocabulary#219]
## Description
A stray span end tag was found on the Vocabulary website, potentially causing issues in the HTML structure. The closing </span> tag is located at line 895 of the index.html file in the docs folder, but it seems misplaced or unnecessary, which could be affecting the proper nesting of HTML elements. This may indicate an extra tag or a typo.

## Reproduction
1. Visit the affected documentation page on the Vocabulary website.
2. Check the index page around line 895.
3. Observe the stray span end tag in the code.

## Expectation
The HTML structure should be correct, with all span tags properly opened and closed in the right places.

## Screenshots
![Screenshot (308)](https://github.com/user-attachments/assets/ac0628b2-d901-4b8e-83c3-203f188852d3)

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by iyinolawumi** [comment]
Thank you @possumbilities and well done @vickova
