### ISSUE TITLE
[Bug] Attribute e Not Allowed on Element article

### ISSUE THREAD

**Issue by vickova** [creativecommons/vocabulary#234]
## Description
- Message: Attribute e not allowed on element article at this point.
- Location: From line 123, column 13 to line 123, column 38 in theprogram-index.html file under the context folder.
- Code Extract: article class="project"e

## Reproduction
- Open the HTML file containing the error.
- Navigate to line 123.
- Observe the article element with an incorrect attribute.
- Verify the error in the console or during validation.

## Expectation
The article element should not have any attributes that are not allowed, such as e. The expected behavior is for the attribute to be removed or corrected.

## Screenshots
![Screenshot (310)](https://github.com/user-attachments/assets/68371fc4-7c5b-4356-97cd-4d24b8f65fd1)

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by vickova** [comment]
Hello, @possumbilities . I observed that you linked a pull request to this issue but it was never closed.

**Comment by Asheklm6** [comment]
Hello @possumbilities i have removed the invalid  attribute from <article> element, as required .
