### ISSUE TITLE
[Feature] Update documentation to reflect changes to footer section

### ISSUE THREAD

**Issue by Queen-codes** [creativecommons/vocabulary#241]
## Problem
A recent change was made to the vocabulary codebase to fix the newsletter validation in PR #180 . The change from this PR has not been reflected in the footer component section of the vocabulary documentation. For users and contributors who go through the documentation, reconciling this difference between the codebase and documentation might be confusing.

## Description
The footer section in the Vocabulary codebase has been updated to remove the empty string in the `required` attribute for the form `input`, and the corresponding documentation for the footer component needs to be modified to reflect its change. This will help maintain consistency between the codebase and its documentation, ensuring that contributors and users can implement the correct footer component.

## Alternatives
An alternative is for users and contributors to always check the codebase for changes.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
@Queen-codes Very good spot!

**Comment by Queen-codes** [comment]
Thank you, @possumbilities. Since this is ready for work now, I was wondering if it would be okay to add a 'good first issue' label so that applicants/contributors interested in making a PR and haven't made one yet can work on this. Would that be okay?

**Comment by egbadon-victor** [comment]
@Queen-codes that's honestly a spot on suggestion!! I'm shook!! While waiting on @possumbilities , you could send the link the the slack channel, so contributors could be notified about it

**Comment by possumbilities** [comment]
@Queen-codes that's also a good suggestion, I added the label!

**Comment by Raja-Abrar-Khan** [comment]
Hey guys i tried to look into it , the required=""  display in the rendered HTML is the standard behavior according to html specifications. This is how browsers represent boolean attributes, and it does not impact the functionality of the input field. @possumbilities  what do you think about this.

**Comment by egbadon-victor** [comment]
@Raja-Abrar-Khan , with reference to issue #180 , the footer has been updated from `required=""` to `required`.

You can checkout the issue to why this was done. The aim of this issue #241 is to reflect these changes in the vocabulary  documentation contained in the `docs/index.html` file

**Comment by Niyatijain-9** [comment]
hey, I want to work on the same. Please assign me this @Queen-codes

**Comment by Queen-codes** [comment]
> hey, I want to work on the same. Please assign me this @Queen-codes

hi @Niyatijain-9 . You can go ahead to create a PR for this issue. I'm also not in the capacity to assign this issue to you or anyone. When and if your PR js merged, it will be assigned to you by the mentor in charge.
