### ISSUE TITLE
[Feature]  Shift All Inline CSS and Scripts to CSS and JS Files for Better Code Readability

### ISSUE THREAD

**Issue by shivam8112005** [creativecommons/vocabulary#247]
## Problem

Currently, the project includes inline CSS and JavaScript directly embedded within the HTML files. This approach makes the code less readable and harder to maintain. It also violates the principle of separating concerns, where HTML should focus on structure, CSS on styling, and JavaScript on functionality.

## Description

This feature proposes moving all inline CSS to external .css files and all inline JavaScript to separate .js files. By doing so, the project will become more modular, easier to maintain, and more readable. It will also facilitate better collaboration, as contributors can work on specific files without needing to navigate through the entire HTML.

## Alternatives

An alternative could be to leave the current inline CSS and JavaScript as is. However, this would continue to make the code harder to manage, especially as the project grows. Externalizing the CSS and JS files will ensure a cleaner structure and make it easier to debug and update in the future.

## Additional context

This change would also help with caching optimization, as browsers cache external CSS and JS files, potentially improving page load times.

## Implementation

- [X] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
@shivam8112005 Can you please document where this is occurring?

**Comment by shivam8112005** [comment]
archive-page.html  loc: 270
blog-post.html  loc: 171
and the div in archive-page.html is common in all file which has inline css. is this done for any reason.
and docs/index.html loc:1023 has script written is that useful?

**Comment by possumbilities** [comment]
@shivam8112005 Thanks for providing that so quickly. However, providing quoted textual examples with accompanying line number is more useful for review.

**Comment by shivam8112005** [comment]
ohk wait

**Comment by shivam8112005** [comment]
### in docs/index.htm



```javascript
1023 <script>
1024  // Escapes HTML within code elements
1025 document.querySelectorAll("code.lang-html").forEach(el => el.innerText = el.innerHTML);
1026  </script>

**Comment by shivam8112005** [comment]
### this div is common in all files this code is from archive-page.html (loc: 270)

```html
265  <div class="subscribe">
266     <h2>Subscribe to our Newsletter</h2>
267      <form action="https://creativecommons.us4.list-manage.com/subscribe/post?u=fd30364b6577b471373d6076c&amp;id=4603fe102a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate newsletter" target="_blank">
268          <input type="email" value="" name="EMAIL" class="email input" id="mce-EMAIL" placeholder="Your email" required>
269          <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
270          <div style="position: absolute; left: -5000px" aria-hidden="true">
271              <input type="text" name="b_fd30364b6577b471373d6076c_4603fe102a" tabindex="-1" value="">
272          </div>
273          <input type="submit" value="subscribe" id="mc-embedded-subscribe" class="button small">
274     </form>
275 </div>

**Comment by possumbilities** [comment]
This would be on purpose, the JS for the docs is so minimal adding a file include at this point, seems more-or-less meaningless. The goal is to keep the docs as simple as possible in implementation for now until we get to resolving a SSG/CMS choice.

> ### in docs/index.htm
> ```js
> 1023 <script>
> 1024  // Escapes HTML within code elements
> 1025 document.querySelectorAll("code.lang-html").forEach(el => el.innerText = el.innerHTML);
> 1026  </script>
> ```

**Comment by possumbilities** [comment]
This is the result of an externally provided vendor snippet, and as such wouldn't be something we'd modify heavily for Vocabulary.

> ### this div is common in all files this code is from archive-page.html (loc: 270)
> ```
> 265  <div class="subscribe">
> 266     <h2>Subscribe to our Newsletter</h2>
> 267      <form action="https://creativecommons.us4.list-manage.com/subscribe/post?u=fd30364b6577b471373d6076c&amp;id=4603fe102a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate newsletter" target="_blank">
> 268          <input type="email" value="" name="EMAIL" class="email input" id="mce-EMAIL" placeholder="Your email" required>
> 269          
> 270          <div style="position: absolute; left: -5000px" aria-hidden="true">
> 271              <input type="text" name="b_fd30364b6577b471373d6076c_4603fe102a" tabindex="-1" value="">
> 272          </div>
> 273          <input type="submit" value="subscribe" id="mc-embedded-subscribe" class="button small">
> 274     </form>
> 275 </div>
> ```

**Comment by possumbilities** [comment]
Lastly you mentioned `blog-post.html loc: 171`:

https://github.com/creativecommons/vocabulary/blob/6ce79f34f0c369905b0911e83541326cea40d428/specimen/contexts/blog-post.html#L169-L175

This is used to simulate how an actual iframe embed would occur which usually comes with inline styling as part of its implementation when provided from a third-party.

**Comment by possumbilities** [comment]
All cases documented here would be on purpose. Thanks for providing a good spot to point to should it come up again, closing as intended behavior.

**Comment by shivam8112005** [comment]
Ohk got it
