### ISSUE TITLE
[Bug] Double Spacing in Paragraph Text of default-page.html

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/vocabulary#248]
## Description
There is an extra space between "a" and "global" in the paragraph text:

https://github.com/creativecommons/vocabulary/blob/6ce79f34f0c369905b0911e83541326cea40d428/specimen/contexts/default-page.html#L57

## Reproduction
1. Navigate to the relevant page or component displaying the text.
2. Locate the paragraph: "Join a global community working to strengthen the Commons."
3. Notice the double space between "a" and "global."
4. See error.

## Expectation
The paragraph should have only a single space between "a" and "global," like this:
`<p>Join a global community working to strengthen the Commons</p>`

## Resolution
 [ ]I would be interested in resolving this bug.

**Comment by SisiVero** [comment]
If it gets accepted., this can be marked as good first issue for new contributors, @possumbilities .

**Comment by jessyovia** [comment]
@SisiVero  I am interested in solving this issue

**Comment by Queen-codes** [comment]
hi @jessyovia . You don't have to ask for issues to be assigned to you. You just go ahead and submit your own PR. However, this particular issue isn't ready for work yet so you can't make a PR. When the label changes to ready for work, then you can  make your PR. When and if this PR is merged, then it will be assigned to you. 

You can read the [Contribution guidelines](https://opensource.creativecommons.org/contributing-code/)

**Comment by jessyovia** [comment]
> If it gets accepted., this can be marked as good first issue for new contributors, @possumbilities .

@Queen-codes Thanks of the feedback

**Comment by SisiVero** [comment]
Hi @jessyovia , did you recall the guides I sent you one time about issue statuses?
I recall sending it via a comment here and on slack too for you. 
Going through them will greatly help.

**Comment by jessyovia** [comment]
> Hi @jessyovia , did you recall the guides I sent you one time about issue statuses? I recall sending it via a comment here and on slack too for you. Going through them will greatly help.

@SisiVero Thank you very much

**Comment by jessyovia** [comment]
> hi @jessyovia . You don't have to ask for issues to be assigned to you. You just go ahead and submit your own PR. However, this particular issue isn't ready for work yet so you can't make a PR. When the label changes to ready for work, then you can make your PR. When and if this PR is merged, then it will be assigned to you.
> 
> You can read the [Contribution guidelines](https://opensource.creativecommons.org/contributing-code/)

@Queen-codes thanks

**Comment by Raja-Abrar-Khan** [comment]
@possumbilities  Assign this issue to me !!
