### ISSUE TITLE
[Bug] Typos in CSS Class and Variable Names

### ISSUE THREAD

**Issue by shivam8112005** [creativecommons/vocabulary#260]
## Description

There are typos in the CSS code of library-vars.css file, including misspelled class names and variables, which result in incorrect icon rendering. For example, fa-angle-right is misspelled as fa-angle-rignt here:https://github.com/creativecommons/vocabulary/blob/746a0de69dd10d04f7d270d1c861bc61cab3c513/src/css/library-vars.css#L204
also here:https://github.com/creativecommons/vocabulary/blob/746a0de69dd10d04f7d270d1c861bc61cab3c513/src/css/library-vars.css#L224
on line 224 class is named  fa-right-angle It should'nt be like fa-angle-right.
## Reproduction

1. In the .icon.fa-angle-right rule, the class name is incorrectly written as .fa-angle-rignt instead of .fa-angle-right.
2. In the .icon.fa-right-angle rule, the variable --fa-heart is mistakenly used for the sprite, but it should be --fa-right-angle.
3. See errors.

## Expectation

The icons should render correctly when using the specified classes when we use it.
## Environment

 - Device: laptop
 - OS: Windows 11
 - Browser: Chrome
 - Version: 117
 - Other info: 1920x1080

## Additional context

The incorrect spelling of class names and variable assignments in the CSS file can cause rendering issues.
## Resolution

- [X] I would be interested in resolving this bug.

**Comment by Immy-delish** [comment]
Hi @shivam8112005 and team,

This issue has been resolved in PR #263, where I fixed the typos in the CSS class names and variable assignments. The changes have been merged, and the icons should render correctly now. Thank you for reporting this!
