### ISSUE TITLE
[Bug] On smaller devices aside bar  appears on top of the post 

### ISSUE THREAD

**Issue by OmarAmeen01** [creativecommons/vocabulary#270]
## Description
the aside  bar containing Related Links and  Categories   is coming before the actual post   on smaller devices which breaks the follow of the page.  while ideally user should first see the post then Related links and category 
## Reproduction

1. Go live on the  archive-page.html
2.  switch to responsive view
3. see the issue

## Expectation
The aside component  should be moved to the bottom of the html structure of post I:e it should come after post syntax .  so that it appears on the bottom of post when user is on smaller devices 

### same feature on Creative commons website 
![HOW IT IS ON OFFICIAL CC WEBSITE ](https://github.com/user-attachments/assets/20a8a266-be57-4b9d-be4c-5534d34dfc2e)
### same feature on our design system 
![HOW IT IS ON OUR SITE](https://github.com/user-attachments/assets/8fada93a-7a9b-4b09-bf64-eea90b32c3cd)

## Environment

 - Device: (iPhone Xs; laptop: Samsung 20)
 - OS: ( iOS 13.5; Android , Windows)
 - Browser: ( Safari; Firefox: Chrome )

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
This is intended behavior for now. The encounter order is set this way so that over time the aside menu can be presented in a collapsed state and be more easily skippable, but it is meant to occur first in markup for the time being.
