### ISSUE TITLE
[Bug] Raw & character should be encoded as "&amp"

### ISSUE THREAD

**Issue by Asheklm6** [creativecommons/vocabulary#282]
## Description

Raw ampersand (&) character in  docs/index.html file are not properly encoded as "&amp" This causes validation errors during HTML validation checks.
## Reproduction

1. Run an HTML validation check using html-validate on the file docs/index.html.
2. Check the error message on line 50,197,313, which reports that the raw & must be encoded as "&amp"
3. Observe the error in the HTML validation report.

## Expectation

The raw & should be encoded as "&amp" to conform to HTML standards, eliminating the validation error and ensuring proper rendering in browsers.
## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x ] I would be interested in resolving this bug.

**Comment by Asheklm6** [comment]
Hello @possumbilities Please can you look into this issue if changes can be made accordingly.

**Comment by OmarAmeen01** [comment]
@Asheklm6  instead addressing one error at time can you list all the errors in one issue so they can be fixed all at once I see lot of error on the docs/index.html total 177 these all can be fixed in one PR .   if you need help I'm ready to help

**Comment by Asheklm6** [comment]
Hii, @OmarAmeen01 ,
Thanks for your feedback, I’ve been raising separate issues because each one is specific to certain HTML files, and I wanted to keep things clear. The earlier ones applied to all HTML files, but this current issue only affects docs/index.html.
I can definitely group them if that makes things easier—just wanted to explain why I separated them initially. 
Appreciate the offer to help.

**Comment by OmarAmeen01** [comment]
yeah you are right I was talking about list all the errors of a specific file as one issue .  I just listed the issue https://github.com/creativecommons/vocabulary/issues/283   that highlights all the issues only in the docs/index.html

**Comment by OmarAmeen01** [comment]
> Hii, @OmarAmeen01 , Thanks for your feedback, I’ve been raising separate issues because each one is specific to certain HTML files, and I wanted to keep things clear. The earlier ones applied to all HTML files, but this current issue only affects docs/index.html. I can definitely group them if that makes things easier—just wanted to explain why I separated them initially. Appreciate the offer to help. 

and are you working on it  I was thinking of raising a PR for this issue

**Comment by Asheklm6** [comment]
Hey @OmarAmeen01,

Thanks for the clarification, I just wanted to mention that some folks have already fixed specific errors in the `.html` files, and those changes have been merged. I’m wondering if the new issue might overlap with that work.

I’d love to make sure we don’t have any conflicts. Maybe it’d be helpful to check what’s already been merged, and we can focus on anything that still needs attention. What do you think?

**Comment by lauracastrotech** [comment]
@OmarAmeen01 @Asheklm6 - I created a PR for this issue by updating the & with the correct encoding

**Comment by Asheklm6** [comment]
Hii, @lauracastrotech I have created a PR to this issue hours ago, i am just awaiting the approval of @possumbilities . But that shouldn't be a big deal as multiple contributions to a particular issue is welcome.

**Comment by Raja-Abrar-Khan** [comment]
@possumbilities  Assign this issue to me !!
