### ISSUE TITLE
[Bug] Img tags not self closing across various contexts

### ISSUE THREAD

**Issue by egbadon-victor** [creativecommons/vocabulary#297]
## Description

With reference to #283 , this focuses on the presence of non closing `img` tags in the following contexts;

- `index.html` file in the docs folder
- `home-index.html` file in the specimen/contexts folder
- `kithensink.html` in the specimen/tests folder 

## Reproduction

1. Fork and clone the repo to your local machine
2. Go to the search pane of your code editor ( VS code in my case)
3. use the following regex to search for non-closing `img` tags; `<img\b[^>]*?(?<!/)>`
4. Observe the non closing `img` tags

## Expectation

You would observe the non closing `img` tags.

## Screenshots

![image](https://github.com/user-attachments/assets/0c2f25de-3a1a-4415-a283-038b8013816a)

## Environment

 - Device: (laptop)
 - OS: (windows)
 - Browser: (chrome)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by shivam8112005** [comment]
@possumbilities I have made pr #300  for this issue

**Comment by egbadon-victor** [comment]
@shivam8112005 awesome work!

**Comment by shivam8112005** [comment]
@egbadon-victor thanks!
