### ISSUE TITLE
[Feature] <The subscribe button under CC  General list doesn't specify errors to be corrected when clicked>

### ISSUE THREAD

**Issue by lillian-busingye** [creativecommons/vocabulary#301]
## Problem
When a user clicks the subscribe button on CC General list, incase some input fields are filled , the error message is generalised and one may not be sure what error is being talked about at the moment. Below is the general error message being described

## Description
<img width="731" alt="footer" src="https://github.com/user-attachments/assets/f81d0208-c8a4-4fd9-866a-72d7b2bd2a8b">

## Alternatives
A simpler solution would be to add an error message (prompt) to each input field incase of such a problem

**Comment by possumbilities** [comment]
Hi @lillian-busingye thanks for your contribution! 

This is an Issue that's already been documented, and the elements which overlap with this repository have been resolved the rest are outside the scope of this project. Please see #121 

Closing as duplicate, in the future please verify that and Issue does not already exist, and has not already been addressed prior to creating one. Please see the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/) for further information.
