### ISSUE TITLE
[Bug] SVG Icon Not Loading in <link> Tag Due to Relative path issue

### ISSUE THREAD

**Issue by shivam8112005** [creativecommons/vocabulary#302]
## Description
The SVG icon is not displaying correctly due to an incorrect relative path in the link tag on archive page.

## Reproduction

1. Include the SVG icon using the following <link> tag in the HTML:
2. Open the webpage in a web browser.
3. Inspect the page to see if the icon is loaded.
4. See error: the icon does not appear in the browser tab or favicon area.

## Expectation

I expected the SVG icon to display correctly as the favicon in the browser tab.

## Screenshots

![Screenshot 2024-10-30 131018](https://github.com/user-attachments/assets/19e02af3-695f-4bfe-acb1-8672baaeb9eb)

## Environment

 - Device: laptop
 - OS: windows 11
 - Browser: chrome
 - Version: 95
 - Other info: 1920x1080

## Additional context

The relative path to the SVG file has been verified, and the file exists at the specified location. However, the icon does not render in the browser tab.

## Resolution

- [X] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
While this is undesired behavior I believe this is just a characteristic of Chrome. Chrome does not display favicons for locally stored web pages. If that's where you are testing this, then this isn't something we could address.

You can see vocabulary implemented on the CreativeCommons.org website, and the favicon does load as expected.

Closing for now.

**Comment by shivam8112005** [comment]
> While this is undesired behavior I believe this is just a characteristic of Chrome. Chrome does not display favicons for locally stored web pages. If that's where you are testing this, then this isn't something we could address.
> 
> You can see vocabulary implemented on the CreativeCommons.org website, and the favicon does load as expected.
> 
> Closing for now.

ohk got it
