### ISSUE TITLE
[Feature] Implementation of an error page context.

### ISSUE THREAD

**Issue by egbadon-victor** [creativecommons/vocabulary#306]
## Problem

As it stands, vocabulary does not specify any standard for styling error pages. Inspecting the various existing error pages on the CC Ancillary sites, some have different implementations.

### CC Legal DB and  Open source
![image](https://github.com/user-attachments/assets/e0136ca4-2d5b-49a4-885e-e3d34d6a8f48)

### CC Search Portal
![image](https://github.com/user-attachments/assets/4ae93141-f69e-4bea-aaa3-e75392ff646a)

## Description

By implementing a standard for CC error pages, it makes it easy to identify error pages that are not properly implemented, as well as serve as a guide for implementation in new projects.

## Alternatives

- Make all error page implementations local to the downstream project (Not recommended)
- Do nothing

## Additional context

This issue is related to;
[[Feature] Error pages are not styled/themed #532](https://github.com/creativecommons/chooser/issues/532)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
This is already covered by:
-  #1

Closing as duplicate.

**Comment by egbadon-victor** [comment]
@possumbilities didn't see it all the way up there 😂.

Ill move my suggestions to that issue. Thank you!
