### ISSUE TITLE
Bug: Unclosed opening <nav> tag in person-page.html file 

### ISSUE THREAD

**Issue by SumaiyaaRq** [creativecommons/vocabulary#313]
## Description
The opening `<nav>` tag is missing the closing angle bracket `(>)`, which prevents proper rendering of the navigation section.
https://github.com/creativecommons/vocabulary/blob/3b23d444c94b81f9d8d7c639031a797410f5718f/specimen/contexts/person-page.html#L226

## Reproduction
 1. Open the person-page.html file using live server
 2. Navigate to footer region
 3. See error

## Expectation
The` <nav>` tag should be properly closed. Since the tag is missing the closing `>`, it is causing improper rendering of the HTML code , leading to layout issues . 
## Screenshots
<img width="1132" alt="Screenshot 2024-11-08 at 10 34 04 PM" src="https://github.com/user-attachments/assets/590242ba-bb40-4026-b7c4-1423f224bc91">

## Environment

 - Device: Laptop
 - OS: macOS
 - Browser: Chrome 
 

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by SumaiyaaRq** [comment]
Hi @rahulptl165 , Thank you for your PR! I really appreciate your effort on this. However, just to clarify, the issue hasn't yet been labeled as `ready for work` . As per the guidelines, we typically wait for that label before starting work on the issue to ensure it's ready for contributors.
I would suggest you to go through the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/) to know how issues and PRs are managed here , it would definitely be helpful for your future contributions to the organization.

**Comment by rahulptl165** [comment]
Hi, @SumaiyaaRq, Thanks for the feedback! I’ll review the Contribution Guidelines to align better with the process. Looking forward to contributing more effectively!
