### ISSUE TITLE
[Formatting] the `vocabulary.js` file has extra empty lines that could do with reduction

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/vocabulary#327]
## Description

Overall, there is use having some level of spacing between sections, but the file has several empty lines both between and within sections that could do with removal.

## Expectation
The file should have appropriate levels of empty lines.

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by rahulptl165** [comment]
hi @possumbilities, I want to work on this Issue. can you assign it to me ?
