### ISSUE TITLE
[Bug] Old twitter logo present in the footer

### ISSUE THREAD

**Issue by Murdock9803** [creativecommons/vocabulary#6]
## Description
The footer has old twitter logo present that needs to be updated.

## Reproduction

1. Go to https://creativecommons.org/
2. Scroll to the bottom of the page.
3. See the old twitter logo at the left side of the footer.

## Expectation
New X logo should be present at the footer.

## Screenshots
![Screenshot 2023-12-23 234528](https://github.com/creativecommons/index-prototype/assets/136724527/22b45ee4-0f4f-4200-a519-1373d48d12b4)

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
Unblocked and resolved by: 
- #319
