### ISSUE TITLE
[Bug] Fix Nested Anchor Tags in Attribution Figure and Improve Semantics

### ISSUE THREAD

**Issue by Annahbellah** [creativecommons/vocabulary#69]
### Description
There’s an issue with the attribution markup in image figures, where nested `<a>` tags are used, causing invalid HTML. This can lead to rendering inconsistencies and affect accessibility. Also, the attribution text is currently placed inside a `<span>`, which is not semantically ideal for this use case
### Reproduction

1. Fix the nested `<a>` tags: Ensure that each link is placed in its own distinct anchor tag.

2. Use `<figcaption>` for better semantics: The attribution text would be better suited inside a `<figcaption>` tag, which is designed to describe the content of the figure element.

### Expectation
The HTML should validate correctly, the markup should be more accessible, and the figure captions should follow proper semantic standards for web content

 ### Screenshots
![Screenshot 2024-10-03 at 10 32 30 AM](https://github.com/user-attachments/assets/f05f1266-ed50-443c-8670-5220f0e7c11d)

### Environment
 - Device: ( laptop)
 - OS: (MacOS Ventura 13.2.1)
 - Browser: (Chrome)
 

### Additional context
This fix will resolve HTML validation issues caused by nested anchor tags and improve semantics and accessibility by using `<figcaption>` for better image description structure.

### Resolution
 I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
@Annahbellah Can you please clarify what you are referring to regarding nested tags, also it seems like you mentioned specific tags in your Issue but did not format them properly so they aren't showing up, could you please correct that as well?

**Comment by possumbilities** [comment]
@Annahbellah `a` elements can be within a `figure` element as it accepts `flow content` as children, so I don't believe there's an issue there. `figcaption` also accepts `flow content` as well.

However, there is a case that the `span` could likely be converted to a `figcaption` element. BUT this is where things get slightly dicey:

> The `<figcaption>` [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a caption or legend describing the rest of the contents of its parent [<figure>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) element, providing the <figure> an [accessible description](https://developer.mozilla.org/en-US/docs/Glossary/Accessible_description).

The official w3c spec, merely leaves it as:

> The [figcaption](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-figcaption-element.html#the-figcaption-element) element [represents](https://www.w3.org/TR/2011/WD-html5-20110525/rendering.html#represents) a caption or legend for the rest of the contents of the [figcaption](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-figcaption-element.html#the-figcaption-element) element's parent [figure](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-figure-element.html#the-figure-element) element.

The attribution listing doesn't fully describe the image and what is within it, but instead meta information about the image (its title, author, etc.).

However, in other instances I have seen the `figcaption` be utilized around a citation when the `figure` is used to contain a `blockquote` and that is also meta information (which is closer to the second definition)

I think in this case the matter is one of a semantic question of whether `figcaption` is more, less, or equally semantic here, and whether attribution information meets the criteria for being a `figcaption`. In thinking about it further, I *think* swapping the `span` for a `figcaption` is likely to be the correct choice, but I'm curious if others have views on this?

**Comment by solonkonora** [comment]
i agree with you sir,
since <figcaption> depends on how closely tied the attribution is to the user's understanding of the content. and i think it is the case here.

**Comment by Annahbellah** [comment]
Thank you all for your thoughtful comments. I will go ahead and replace <span> with <figcaption> so as to improve the semantics.

**Comment by possumbilities** [comment]
Work here would need to address this in all locations within Vocabulary, and also fully ensure that it does not cause rendering disruption.

**Comment by Annahbellah** [comment]
Noted @possumbilities

**Comment by egbadon-victor** [comment]
@possumbilities while the text may not directly describe the image being referenced, the intention is for the text to be related or "paired" with the image.  

As the official documentation does not explicitly describe a caption, I believe the contents of the `span` can be considered as a caption and hence, the `span` tag can be replaced with a `figcaption` tag.
