### ISSUE TITLE
[Feature] Create Reusable Navbar and Footer Using JavaScript for Code Consistency and Maintenance

### ISSUE THREAD

**Issue by Vanessa082** [creativecommons/vocabulary#74]
## Problem
Currently, each HTML page contains separate code for the navbar and footer, leading to code redundancy and making it difficult to maintain consistent changes across the site.

## Description
Create separate `navbar.html` and `footer.html` files that contain the HTML code for the navbar and footer. Use JavaScript to dynamically load these components into each page, reducing redundancy and simplifying future maintenance. This will make the code more modular and reduce the effort needed to make changes to the navbar or footer across the website.

## Alternatives
1. **Manually updating the navbar and footer on each page**: This approach leads to increased maintenance effort and a higher chance of inconsistencies.
2. **Copy-pasting navbar and footer code into each page**: This can work but lacks the maintainability benefits of reusable, dynamically loaded components.

Using JavaScript to load a single navbar and footer file ensures consistency across all pages and makes updates efficient and straightforward.

## Additional context
The implementation uses JavaScript `fetch()` to load the navbar and footer HTML files into each page dynamically. This ensures that both components remain consistent across all pages without duplicating code.

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
Thank you for your excitement and contribution! 

However, the Vocabulary system uses static HTML and avoids the overuse of JavaScript for a number of reasons (particularly in these cases). This kind of change is not in alignment with the project. 

Closing.
