### ISSUE TITLE
[Bug] Missing Image in some html pages.

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/vocabulary#84]
## Description
The image src throws and error that the image file does not exist, thereby causing a break in the interface.

## Expectation
It probably is a mistake as the source of the image (the image file- imgs) is missing

## Screenshots
Attached is a screengrab of the broken interface:

<img width="587" alt="DefaultPageImgError" src="https://github.com/user-attachments/assets/fe3855ef-cc55-4dff-8231-8afb1f863b55">

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
This is known and a largely a duplicate of #39. 

Closing for now as it overlaps.
