### ISSUE TITLE
[Bug] Inconsistent image height in Blog page.

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/vocabulary#86]
## Description
Inconsistent image height in Blog page. This in a way reduces how good the interface is.

## Expectation
Give the images same height to promote consistency

## Screenshots
Attached is screenshot from the live website (the img src is currently broken, I've opened an issue for it):

<img width="910" alt="blogImageHeight" src="https://github.com/user-attachments/assets/e8ae2c3d-0561-4db4-84e4-5e172cfb4fd3">

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
This is an issue with the images not being the correct dimensions when uploaded to the main CreativeCommons.org site, and isn't an issue directly related to Vocabulary itself at this time.

Closing.
