### ISSUE TITLE
Documentation Discrepancy in Header - Global Area Code Example

### ISSUE THREAD

**Issue by Sophiek9h** [creativecommons/vocabulary#94]
## Problem
The "Header - Global Area" section in the Vocabulary documentation contains a code example under "Expected Contexts" that does not match the actual implementation in the codebase. This inconsistency can confuse developers trying to use the correct structure when implementing the header.

## Description
The documentation provides a sample structure for the Global Header, including sub-elements such as Masthead, Primary Nav Menu, and Explore Panel. However, the provided example is different from the current implementation in the repository. Specifically in the menu options

## Alternatives
Alternatively, if the structure in the codebase is intended to be different, consider updating the code to match the documented format.

## Additional context
This issue was noticed when reviewing the header code in the codebase, specifically within the implementation of the global header component. Ensuring alignment between the documentation and the codebase will improve clarity for developers working with Vocabulary.

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
Hi and thanks for this contribution! 

Vocabulary's documentation is meant to be generalized as examples and implemented on sites that would have different menu contexts. There wouldn't be a way to address this and make it consistent. There is no singular header + menus configuration that would be identical in all situations.

The only route of solution I can think of here is that we could include some note when the Components section begins that these are meant to be examples, and not necessarily 1:1 reference specs, and then list the header as a notable example of that pattern.

**Comment by Sophiek9h** [comment]
@possumbilities Thanks for the feedback 
can I go ahead to include a note in the component section just before the header to explain that the codes in the component section are just examples

**Comment by possumbilities** [comment]
@Sophiek9h I think that would be helpful!
