### ISSUE TITLE
[Bug & Feature] Navbar scrolls with page.

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/vocabulary#98]
## Description
**What is the essence of a navbar?**

The essence of a navbar is to enable users easily navigate to different pages in the webapp or website.
Currently, the navbar scrolls to the top and out of view when a user scrolls to the bottom of the page, now, what if a user wants to navigate to another page? He or she would have to scroll to the top to able to see the navbar and navigate to the desired page.
This is a not a good UX.

Suggestion:
The navbar should be in a fixed position, so that whether the user scrolls to the bottom of the page, he or she can easily without stress navigate to other pages.
This feature is implemented by most websites. You can checkout the [outreachy](https://www.outreachy.org/) website too, scroll to the bottom of the page. Did you notice anything with the navbar? That's it!.

- [x] I would be interested in resolving this bug and adding the feature.

**Comment by possumbilities** [comment]
Hi and thanks for this! You've definitely identified a problem but I'm not sure the suggested route of solution would work.

Adding a sticky menu is not a feature within scope for this project, it comes with a number of additional issues that have to worked around from a UX and Accessibility standpoint. However, a route of solution here would likely go through the introduction of a `scroll-to-top` button as featured here: #54 

Closing this as mostly an overlap with the work in #54
